language: android

# To use Travis Container-Based Infrastructure
sudo: false

env: BUILD_TOOLS=22.0.1 ANDROID_API=android-21 ANDROID_ABI=armeabi-v7a

cache:
  directories:
   - $HOME/.gradle/caches/

matrix:
  fast_finish: true

android:
  components:
    - platform-tools
    - tools
    - build-tools-${BUILD_TOOLS}
    - ${ANDROID_API}
    - extra-google-google_play_services
    - extra-android-m2repository
    - extra-google-m2repository
    - sys-img-armeabi-v7a-${ANDROID_API}

before_script:
  # tell dx to use less memory, since we're running out of it
  - sed -i 's/defaultMx="-Xmx1024M"/defaultMx="-Xmx512M"/' /usr/local/android-sdk/build-tools/${BUILD_TOOLS}/dx

  - echo no | android create avd --force -n testAvd -t ${ANDROID_API} --abi ${ANDROID_ABI}
  - emulator -avd testAvd -no-audio -no-window &
  - android-wait-for-emulator
  - adb devices
  - adb shell input keyevent 82 &

script:
  - ./gradlew assemble connectedAndroidTestDevelopment

deploy:
  provider: releases
  api_key:
    secure: Si6dy+ETFBwsbbjMOd9WI8ho0TMDnL46/vhKxLc5Rlvh75UUZH/ThEht/eRhZBP4IgEyg1oeR/8NOL8Lg70aA/cnv0c1+3u050MrUgDIMbbVwgo/l1v7CXfHvRYmicwcn5l9+qhcVaS3Lp7rftfeEvUgXLwwPS0kRxHZuINIYw8=
  file_glob: true
  file: ${HOME}/build/${TRAVIS_REPO_SLUG}/App/build/outputs/apk/lokki-production-v*-debug.apk
  skip_cleanup: true
  on:
    tags: true
    branch: master
    repo: TheSoftwareFactory/lokki-android

notifications:
  slack:
    secure: eV5cEvPOZnp8ZK20CEI+0jt9VUxbtWpJJiSmo17C8TgL4MO5j0rjIBiDOMJhVExMEHxF9AZBCvXNEm1sozNv2VEt755QSPwqA6DTRswKmVQ1LWCOko4UWi3RF8rfSKPTPxAe5JM7Scm6SJQ8aQSIeXD6R8kw4nH6DbzuL/icqv0=
  email: false
